    <div class="chat-box">
        <div class="contact-box">
            <form method="get" name="search-form" class="search-form" action="search.php">
                <input type="text" name="q" value="<?= isset($query) ? $query : '' ?>">
                <button type="submit">Search</button>
            </form>

            <ul class="contacts">
                <?php if (isset($contacts) and !empty($contacts)) : ?>
                    <?php foreach($contacts as $contact) : ?>
                        <li class="<?= (isset($messages['with']) and $contact->getContact() == $messages['with']) ? 'checked' : '' ?>"><a data-with="<?= $contact->getContact() ?>" href="conversation.php?with=<?= $contact->getContact() ?>"><label><?= $contact->getName() ?></label></a></li>
                    <?php endforeach; ?>
                <?php else : ?>
                    <span class="contacts-not-found">Nothing found</span>
                <?php endif; ?>
            </ul>
        </div>
        
        <div class="conversation">
            <div class="messages-container">
                <?php if (isset($messages['with'])) : ?>
                    <?php if ($messages['count'] < $messages['totalCount']) :?>
                        <div class="get-more-messages">
                            <label><a data-with="<?= $messages['with'] ?>" data-offset="<?= $messages['offset'] + 1 ?>" href="conversation.php?with=<?= $messages['with'] ?>&offset=<?= $messages['offset'] + 1 ?><?= (isset($messages['messages'][0])) ? '#message-' . $messages['messages'][0]->getId() : '' ?>">Get more messages</a></label>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
                <div class="messages">
                    <?php if (isset($messages['with'])) : ?>
                        <?php if (isset($messages['p'])) : ?>
                            <?php if ($messages['p']['passphrase']) : ?>
                                <?php if (isset($messages['messages'])) : ?>
                                    <?php foreach ($messages['messages'] as $message) : ?>
                                        <div id="message-<?= $message->getId() ?>" data-message-id="<?= $message->getId() ?>" class="message">
                                            <span class="date"><?= $message->getDate() ?></span>
                                            <div class="message-container">
                                                <div class="author"><a href="user.php?id=<?= $message->getAuthor() ?>"><?= htmlspecialchars($message->getName()) ?></a></div>
                                                <div class="content"><?= nl2br(htmlspecialchars($message->getContent())) ?></div>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            <?php else : ?>
                                <div class="enter-passphrase">
                                    <form method="post" name="passphrase" data-with="<?= $messages['with'] ?>" data-offset="<?= $messages['offset'] ?>" action="conversation.php?with=<?= $messages['with'] ?>&offset=<?= $messages['offset']?>" class="passphrase-form">
                                        <label>
                                            Passphrase
                                            <input type="password" name="passphrase" pattern="(.){6,128}" required>
                                            <span class="passphrase-error">
                                                <?= (isset($messages['p']['error']) ? $messages['p']['error'] : '' ) ?>
                                            </span>
                                        </label>
                                    </form>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php else : ?>
                        <div class="select-dialog">Select Dialog</div>
                    <?php endif; ?>
                </div>
            </div>

            <?php if (isset($messages['with'])) : ?>                
                 <form method="post" name="message-form" class="message-form" data-send-to="<?= $messages['with'] ?>"" action="send.php?to=<?= $messages['with'] ?>">
                    <textarea name="message"></textarea>

                    <input type="hidden" name="token" value="<?= $_COOKIE['token'] ?>">

                    <input type="submit" name="submit" value="Send">
                 </form>
             <?php endif; ?>
        </div>
    </div>