    <div class="chat-box">
        <div class="contact-box">
            <form method="get" name="search-form" class="search-form" action="search.php">
                <input type="text" name="q" value="<?= isset($query) ? $query : '' ?>">
                <button type="submit">Поиск</button>
            </form>

            <ul class="contacts">
                <?php if (isset($contacts) and !empty($contacts)) : ?>
                    <?php foreach($contacts as $contact) : ?>
                        <li class="<?= (isset($messages['with']) and $contact->getId() == $messages['with']) ? 'checked' : '' ?>"><a data-with="<?= $contact->getId() ?>" href="conversation.php?with=<?= $contact->getId() ?>"><label><?= $contact->getName() ?></label></a></li>
                    <?php endforeach; ?>
                <?php else : ?>
                    <span class="contacts-not-found">Ничего не найдено</span>
                <?php endif; ?>
            </ul>
        </div>
        
        <div class="conversation">
            <div class="messages-container">
                <?php if (isset($messages['with'])) : ?>
                    <?php if ($messages['count'] < $messages['totalCount']) :?>
                        <div class="get-more-messages">
                            <label><a data-with="<?= $messages['with'] ?>" data-offset="<?= $messages['offset'] + 1 ?>" href="conversation.php?with=<?= $messages['with'] ?>&offset=<?= $messages['offset'] + 1 ?><?= (isset($messages['messages'][0])) ? '#message-' . $messages['messages'][0]->getId() : '' ?>">Получить больше сообщений</a></label>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
                <div class="messages">
                    <?php if (isset($messages['with'])) : ?>
                        <?php if (isset($messages['messages'])) : ?>
                            <?php foreach ($messages['messages'] as $message) : ?>
                                <div id="message-<?= $message->getId() ?>" data-message-id="<?= $message->getId() ?>" class="message">
                                    <span class="date"><?= $message->getDate() ?></span>
                                    <div class="message-container">
                                        <div class="author"><a href="user.php?id=<?= $message->getAuthor()->getId() ?>"><?= htmlspecialchars($message->getAuthor()->getName()) ?></a></div>
                                        <div class="content"><?= nl2br(htmlspecialchars($message->getContent())) ?></div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    <?php else : ?>
                        <div class="select-dialog">Выбирите диалог</div>
                    <?php endif; ?>
                </div>
            </div>

            <?php if (isset($messages['with'])) : ?>                
                 <form method="post" name="message-form" class="message-form" data-send-to="<?= $messages['with'] ?>"" action="send.php?to=<?= $messages['with'] ?>">
                    <textarea name="message"></textarea>

                    <input type="hidden" name="token" value="<?= $_COOKIE['token'] ?>">

                    <input type="submit" name="submit" value="Отправить">
                 </form>
             <?php endif; ?>
        </div>
    </div>